### ISSUE TITLE
sort_vcf_same_as_bam.sh doesn't work with compressed files

### ISSUE THREAD

**Issue by KrisDavie** [aertslab/popscle_helper_tools#2] opened 2020-08-18 11:03 UTC
It seems like sort_vcf_same_as_bam.sh will correctly extract the header etc. from a vcf.gz file, but when the reheader runs, the header is uncompressed and the vcf is compressed, I ended up with a gzipped file which had a plain text header when uncompressed, but the remaining VCF was still gzipped. My quick solution was to alter line 181 to
```
        <(zcat "${vcf_input_file}") \
```
but then this will only work on gzipped files. A solution to detect and use the correct procedure would be good.

**Comment by ghuls** [comment] 2020-08-19 10:26
Should be fixed in https://github.com/aertslab/popscle_helper_tools/commit/f385d24f1b6ef9e5700f17eeb873eed676ecc25e

Looks like there is a bug in `bcftools reheader` while streaming the output file:
https://github.com/samtools/bcftools/issues/1288

**Comment by ghuls** [comment] 2020-09-03 14:39
The problem is fixed in the lastest git version of bcftools. Gzipped VCF files are not supported by `bctools reheader`, only plain VCF, BCF, or BGZF-compressed VCF or BCF files. The new version of bcftools will give an error message for gzipped VCF files.

**Closed as completed** 2021-01-28 09:00 UTC
